// <auto-generated />
using BunnyBot.Resources.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BunnyBot.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20180616210112_AddVotesToDb")]
    partial class AddVotesToDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("BunnyBot.Resources.Database.Vote", b =>
                {
                    b.Property<ulong>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Ammount");

                    b.HasKey("UserId");

                    b.ToTable("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
